apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aet-request.client.fullname" . }}
  labels:
    {{- include "aet-request.labels" . | nindent 4 }}
    app.kubernetes.io/component: client
spec:
  {{- if not .Values.client.autoscaling.enabled }}
  replicas: {{ .Values.client.replicaCount }}
  {{- end }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      {{- include "aet-request.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: client
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/client-configmap.yaml") . | sha256sum }}
      labels:
        {{- include "aet-request.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: client
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: client
          image: "{{ .Values.client.image.repository }}:{{ .Values.client.image.tag }}"
          imagePullPolicy: {{ .Values.client.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "aet-request.client.fullname" . }}
          ports:
            - name: http
              containerPort: {{ .Values.client.service.targetPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
          {{- if .Values.otel.client.nginxProxy.enabled }}
          volumeMounts:
            - name: nginx-otel-conf
              mountPath: /etc/nginx/extra.d/otel-proxy.conf
              subPath: otel-proxy.conf
          {{- end }}
          resources:
            {{- toYaml .Values.client.resources | nindent 12 }}
      {{- if .Values.otel.client.nginxProxy.enabled }}
      volumes:
        - name: nginx-otel-conf
          configMap:
            name: {{ include "aet-request.client.fullname" . }}-nginx
      {{- end }}
