apiVersion: v1
kind: Service
metadata:
  name: {{ include "aet-request.server.fullname" . }}
  labels:
    {{- include "aet-request.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: {{ .Values.server.service.targetPort }}
      protocol: TCP
      name: http
    - port: {{ .Values.otel.server.metricsPort }}
      targetPort: {{ .Values.otel.server.metricsPort }}
      protocol: TCP
      name: metrics
  selector:
    {{- include "aet-request.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: server
